### ISSUE TITLE
Music stops as soon as the world loading animation shows up.

### ISSUE THREAD

**Issue by frikinjay** [sekwah41/While-We-Wait#11]
I came across an issue with the While We Wait 1.17 mod, the music stops as soon as the world loading animation shows up.

**Comment by itsmorethantech** [comment]
It happens with me too

**Comment by sekwah41** [comment]
I actually haven't toyed with 1.17.1 at all, ill need to pull it down and take a look as someone else made a pr for the port :P

**Comment by sekwah41** [comment]
Ok ive found the issue, mc calls stopAll because of some changes to the menus. I have altered it to show during the progress screen but need to look into a better fix at some point. Otherwise it would just keep starting and stopping each time it gets to one of those events.
