### ISSUE TITLE
Music just loops the first few seconds

### ISSUE THREAD

**Issue by Shnupbups** [sekwah41/While-We-Wait#3]
In recent versions, the music never plays in its entirety, instead skipping back to the beginning each time it gets a few seconds in.

**Comment by sekwah41** [comment]
I will take a look at this issue tomorrow and supply a fix or ask for more info on the mods involved if I cannot find this.

**Comment by sekwah41** [comment]
Seems to be a bug in how the minecraft audio is now tracked. If the sound is streaming at this point it keeps looping over the starting frames from the audio. For now I will swap the audio off from streaming and upload a fix.
